name: winwincinema

services:
  winwincinema.api:
    image: ${DOCKER_REGISTRY-}winwincinemaapi
    build:
      context: WinWinCinema.Api
      dockerfile: Dockerfile
    depends_on:
        - sql
    environment:
        - ASPDOTNETCORE_ENVIRONMENT=Development
  sql: 
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Your_password123"
        MSSQL_PID: "Express"
    ports: 
     - "1433:1433"